image: python:3.8

stages:
  - deploy

before_script:
  - git submodule update --init --recursive
  # Install necessary dependencies
  - pip install --upgrade pip
  - pip install packaging
  - wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_0.111.3_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar -xvf hugo.tar.gz
  - mv hugo /usr/local/bin/hugo

pages:
  stage: deploy
  script:
    - hugo --baseURL=https://ida-mdc.gitlab.io/workshops/workshop-template
  artifacts:
    paths:
      - public
  only:
    - main
